name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  Build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.10.1'
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: '4.1.0'

      - name: Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get install libpoppler-cpp-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libglu1-mesa-dev
          sudo apt-get install libmagick++-dev
          sudo apt-get install libharfbuzz-dev
          sudo apt-get install libfribidi-dev

      - name: Install pandoc filters
        run: |
          python -m pip install --upgrade pip
          pip install pandoc-fignos pandoc-eqnos pandoc-tablenos pandoc-secnos pandoc-xnos
          which pandoc pandoc-fignos pandoc-eqnos pandoc-tablenos pandoc-secnos pandoc-xnos

      - name: Install LaTeX
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install texlive-latex-extra
          sudo apt-get install texlive-xetex

      - name: Install R dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: make install

      - name: build project
        run: make manuscript

      - name: prepare deployment
        run: |
          mv docs/manuscript.html docs/index.html
      
      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
          single-commit: true
